language: php

sudo: false

php:
  - 5.6
  - 7.0
  - 7.1
  - nightly
  - hhvm

env:
  - PHPUNIT=5.7.*
  - PHPUNIT=6.0.*
  - PHPUNIT=6.1.*
  - PHPUNIT=6.2.*

cache:
  directories:
    - $HOME/.composer

before_script:
  - phpenv config-rm xdebug.ini || true
  - composer self-update
  - composer require phpunit/phpunit:${PHPUNIT}

script:
  - ./bin/phpunit
